name: Run tests for camel bleuprint
on:
  push:
jobs:
  compilation_and_unit_tests:
    runs-on: ubuntu-latest
    name: "Compilation and unit tests"
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: cd camel-rest && mvn clean install